### ISSUE TITLE
Trouble getting a sensible reading

### ISSUE THREAD

**Issue by TrystanLea** [priveros/Elster_A1100#3]
Hello Priveros

Thankyou for writing this library, I've been trying to get it to work here and Im not having much luck, I seem to be reading something from the meter but its not decoding sensibly.

After a fair bit of digging I worked out that the bit period on my meter was 416us so I set #define BIT_PERIOD 416 and that I needed to use attachInterrupt(1, onPulse, RISING);  rather than the lower level registers to read anything.

With debug enabled I am getting the output below, but it looks like its not quite decoding correctly, sorry for the long print out, it is updated every 4s and seems to be quite consistent.

I have been testing with the TSL261r and our optical reader that works with the a100c https://shop.openenergymonitor.com/optical-utility-meter-led-pulse-sensor. I have also now ordered the RPM7138-R.

Does the output below look familiar? do you think it could be a sensor issue? or a different elster meter data packet format/order?

---->>>>138686816.00    140819280.00    17  10  10101   100001  [329:AE][330:BF][331:B][332:BA][333:EB][334:BF][335:B][336:BA][337:AB][338:BF][339:EB][340:BB][341:AB][342:BF][343:AB][344:BF][345:AB][346:BF][347:AB][348:BF][349:AB][350:BF][351:AB][352:BF][353:BF][354:BF][355:B][356:BA][357:BB][358:BF][359:FF][360:87][361:FC][362:BF][363:EB][364:87][365:EF][366:2B][367:BA][368:BF][369:B][370:BA][371:EB][372:BF][373:B][374:BA][375:AB][376:BF][377:EB][378:BB][379:AB][380:BF][381:AB][382:BF][383:AB][384:BF][385:AB][386:BF][387:AB][388:BF][389:AB][390:BF][391:AB][392:BF][393:B][394:BA][395:AB][396:BF][397:FF][398:87][399:FC][400:BF][401:EB][402:87][403:EF][404:2B][405:EE][406:BF][407:85][408:BF][409:B][410:BA][411:BD][412:BF][413:B][414:BA][415:AB][416:BF][417:EB][418:BB][419:AB][420:BF][421:AF][422:BF][423:EF][424:2B][425:EE][426:BF][427:85][428:BF][429:B][430:BA][431:AD][432:BF][433:B][434:BA][435:AB][436:BF][437:EB][438:BB][439:AB][440:BF][441:AB][442:BF][443:EF][444:2B][445:EE][446:BF][447:FD][448:BF][449:B][450:BA][451:EF][452:BF][453:FD][454:BF][455:B][456:BA][457:AB][458:BF][459:EB][460:BB][461:AB][462:BF][463:AB][464:BF][465:EF][466:2B][467:EE][468:BF][469:85][470:BF][471:B][472:BA][473:EB][474:BF][475:B][476:BA][477:AF][478:BF][479:EB][480:BB][481:AB][482:BF][483:AB][484:BF][485:AB][486:BF][487:AB][488:BF][489:AB][490:BF][491:BD][492:BF][493:EB][494:AF][495:BB][496:FD][497:BF][498:FD][499:EF][500:2B][501:EE][502:BF][503:85][504:BF][505:B][506:BA][507:EB][508:BF][509:B][510:BA][511:BB][512:BF][513:EB][514:BB][515:AB][516:BF][517:AB][518:BF][519:AB][520:BF][521:AB][522:BF][523:AB][524:BF][525:AB][526:BF][527:EB][528:AF][529:BB][530:FD][531:BF][532:FD][533:EF][534:2B][535:EE][536:BF][537:85][538:BF][539:B][540:BA][541:FD][542:BF][543:B][544:BA][545:AB][546:BF][547:EB][548:BB][549:AB][550:BF][551:AB][552:BF][553:AB][554:BF][555:AB][556:BF][557:AF][558:BF][559:EB][560:BF][561:EF][562:2B][563:EE][564:BF][565:85][566:BF][567:B][568:BA][569:BD][570:BF][571:BB][572:BF][573:B][574:BA][575:AB][576:BF][577:EB][578:BB][579:AB][580:BF][581:AB][582:BF][583:AB][584:BF][585:AB][586:BF][587:AB][588:BF][589:AB][590:BF][591:EF][592:2B][593:EE][594:BF][595:85][596:BF][597:B][598:BA][599:BD][600:BF][601:BF][602:BF][603:B][604:BA][605:AB][606:BF][607:EB][608:BB][609:AB][610:BF][611:AB][612:BF][613:AB][614:BF][615:AB][616:BF][617:AB][618:BF][619:AB][620:BF][621:EF][622:2B][623:EE][624:BF][625:85][626:BF][627:B][628:BA][629:BD][630:BF][631:AD][632:BF][633:B][634:BA][635:AB][636:BF][637:EB][638:BB][639:AB][640:BF][641:AB][642:BF][643:AB][644:BF][645:AB][646:BF][647:AB][648:BF][649:AB][650:BF][651:EF][652:2B][653:BE][654:1B][655:EE][1:BB][2:AB][3:A][4:A8][5:BB][6:AD][7:BB][8:1B][9:EE][10:BF][11:85][12:BF][13:B][14:BA][15:AF][16:BF][17:B][18:BA][19:AF][20:BF][21:EB][22:BB][23:BD][24:AD][25:5A][26:82][27:BF][28:FD][29:AF][30:FD][31:BF][32:85][33:BB][34:FD][35:AB][36:BB][37:AF][38:AD][39:AF][40:BF][41:AF][42:BF][43:AB][44:BF][45:AB][46:BF][47:EF][48:2B][49:AA][50:BF][51:B][52:BA][53:BB][54:BF][55:B][56:BA][57:AB][58:BF][59:EB][60:BB][61:BB][62:BF][63:7B][64:BA][65:AB][66:BF][67:AF][68:BF][69:AF][70:BF][71:85][72:BF][73:85][74:BF][75:7B][76:BA][77:7B][78:AB][79:EF][80:2B][81:EE][82:BF][83:85][84:BF][85:B][86:BA][87:AF][88:BF][89:B][90:BA][91:AB][92:BF][93:EB][94:BB][95:AB][96:BF][97:AB][98:BF][99:AB][100:BF][101:AB][102:BF][103:AB][104:BF][105:AB][106:BF][107:EF][108:2B][109:AA][110:BF][111:B][112:BA][113:AB][114:BF][115:B][116:BA][117:AB][118:BF][119:EB][120:BB][121:7B][122:BA][123:7B][124:BA][125:7B][126:BA][127:7B][128:BA][129:7B][130:BA][131:7B][132:BA][133:7B][134:BA][135:7B][136:BA][137:AF][138:BF][139:BD][140:BF][141:AB][142:BF][143:EB][144:BF][145:AF][146:BF][147:85][148:BF][149:85][150:BF][151:AD][152:BF][153:EF][154:2B][155:AA][156:BF][157:B][158:BA][159:BB][160:BF][161:B][162:BA][163:AF][164:BF][165:EB][166:BB][167:AB][168:BF][169:AB][170:BF][171:AB][172:BF][173:AB][174:BF][175:EF][176:2B][177:AE][178:BF][179:B][180:BA][181:EB][182:BF][183:B][184:BA][185:AF][186:BF][187:EB][188:BB][189:AB][190:BF][191:AB][192:BF][193:AB][194:BF][195:AB][196:BF][197:AB][198:BF][199:AB][200:BF][201:BF][202:BF][203:B][204:BA][205:BB][206:BF][207:FF][208:87][209:FC][210:BF][211:EB][212:87][213:EF][214:2B][215:BA][216:BF][217:B][218:BA][219:EB][220:BF][221:B][222:BA][223:AF][224:BF][225:EB][226:BB][227:AB][228:BF][229:AB][230:BF][231:AB][232:BF][233:AB][234:BF][235:AB][236:BF][237:AB][238:BF][239:AB][240:BF][241:B][242:BA][243:AB][244:BF][245:FF][246:87][247:FC][248:BF][249:EB][250:87][251:EF][252:2B][253:AE][254:BF][255:B][256:BA][257:EB][258:BF][259:B][260:BA][261:BB][262:BF][263:EB][264:BB][265:AB][266:BF][267:AB][268:BF][269:AB][270:BF][271:AB][272:BF][273:AB][274:BF][275:AB][276:BF][277:AB][278:BF][279:B][280:BA][281:AB][282:BF][283:FF][284:87][285:FC][286:BF][287:EB][288:87][289:EF][290:2B][291:BA][292:BF][293:B][294:BA][295:EB][296:BF][297:B][298:BA][299:BB][300:BF][301:EB][302:BB][303:AB][304:BF][305:AB][306:BF][307:AB][308:BF][309:AB][310:BF][311:AB][312:BF][313:AB][314:BF][315:AB][316:BF][317:B][318:BA][319:AB][320:BF][321:FF][322:87][323:FC][324:BF][325:EB][326:87][327:EF][328:2B]

**Comment by priveros** [comment]
Hi Tristan,

If your meter is the a100c the IR message is quite different. Have had look at Dave's site:
http://www.rotwang.co.uk/projects/meter.html

He has documented a working solution for that specific  meter.

As per the output I would tell that your sensor is getting readings there. But the decoding the message is very different for the elster a100c than the elster A1100

If you are interested still in the process of how is this decoded for the A1100 look at this repository
https://github.com/priveros/MeterReaderElsterA1100WIFI

There I have loaded many of the xls files I use in the decoding an understanding of the IR message. In that library  as well you have a bit better decoding function of the IR readings.

I would recommend to read the meter manual section about the IRDAx message. 

Cheers

Pedro

**Comment by TrystanLea** [comment]
Hello Pedro, sorry I was not clear enough above it is the a1100 Im trying to read, I can read the a100c fine with Dave's work. I've tested with the RPM7138-R too and still no luck. I will have a look at your files on decoding the message, thanks!

**Comment by TrystanLea** [comment]
Hello Pedro, Im still having no luck with this. I have tried a variety of BIT_PERIOD's and tried a whole set of modifications here and there but nothing sensible is coming out.

Would you expect with the correct BIT_PERIOD set and using the first part of Dave Berkeley's code as below the correct characters to be printed out?

#include "elster.h"

void meter_reading(unsigned long r) { }
ElsterA100C meter(meter_reading);

void setup()
{
  Serial.begin(115200);
  meter.init(1);
}
void loop()
{
  const int c = meter.decode_bit_stream();
  if (c != -1) {
    Serial.print(c);
    Serial.print(",");
    if (c==1) Serial.println();
  }
}

Im looking for a message starting with 1 or 0x01 the SOH but I very rarely get a SOH character..

**Comment by priveros** [comment]
Hi Tristan, I wouldn't think Dave's code can be easily mix to mine. If your arduino wiring is correct  I would start debugging how often you are getting those interrupts. You should see every 4 seconds a IR message ( the actual message is not too long let's say a second) It's been more than a year without looking this. After that period of no signals you should expect the start of message. If I can't detect this pattern something maybe wrong with your wiring. I was writing a blog at that time where the wiring is explained hava you seen that?

**Comment by TrystanLea** [comment]
Hello Pedro, yes pretty sure I got it all right, I followed your blog here: https://pedrosnotes.wordpress.com/2015/09/26/decoding-electricity-meter-elster-a1100-first-steps. I think I should perhaps try an off the shelf reader as a sanity check..

**Comment by priveros** [comment]
Nice, by the way I did some updates on that page few days ago. also, working to do a new post just for the decoding part...(that was fun part of the project) hope I can finish it soon, if life doesn't get in the way.
